name: widget_test_harness
description: Create a reusable harness for testing.  Use Mixins to combine functionality to keep testing dependencies dry
repository: https://github.com/aanelson/shiken
version: 0.7.4

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  golden_toolkit: ^0.15.0
  provider: ^6.0.5
