name: widget_test_harness
description: Create a reusable harness for testing.  Use Mixins to combine functionality to keep testing dependencies dry
repository: https://github.com/aanelson/shiken
version: 0.2.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  collection: ^1.17.0
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter


dev_dependencies:
  flutter_lints: ^2.0.1
  provider: ^6.0.5
